export const INITIAL_MENU_ITEMS = [
  {
    name: "Amritsari Kulcha",
    description: "Crisp multi-layered flatbread stuffed with spiced potatoes and crushed pomegranate seeds, served with chole and churned white butter.",
    price: 249,
    category: "Breads",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: true,
    available: true,
    featured: true,
  },
  {
    name: "Tandoori Chicken",
    description: "Tender spring chicken steeped in hung curd, Kashmiri deggi mirch, and mustard oil, charred over smoking coal embers.",
    price: 449,
    category: "Tandoor",
    image: "/dishes/tandoori_chicken.jpg",
    vegetarian: false,
    spicy: true,
    available: true,
    featured: true,
  },
  {
    name: "Dal Makhani",
    description: "Black lentils and kidney beans simmered overnight for 18 hours with vine-ripened tomatoes, finished with churned butter and sweet cream.",
    price: 299,
    category: "Veg",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: true,
  },
  {
    name: "Butter Chicken",
    description: "Succulent charcoal-grilled chicken tikka bathed in an unctuous, silky gravy of roasted tomatoes, cashews, and dried fenugreek.",
    price: 399,
    category: "Non-Veg",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    vegetarian: false,
    spicy: false,
    available: true,
    featured: true,
  },
  {
    name: "Paneer Tikka Angare",
    description: "Thick cubes of fresh malai paneer marinated in yellow chilli paste, ajwain, and hung curd, blistered in the clay tandoor.",
    price: 329,
    category: "Tandoor",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: true,
    available: true,
    featured: false,
  },
  {
    name: "Sarson Ka Saag & Makki Roti",
    description: "Hand-crushed winter mustard greens cooked with radish and ginger, crowned with homemade makhan and cornflour flatbreads.",
    price: 349,
    category: "Veg",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  },
  {
    name: "Rara Gosht",
    description: "Slow-braised mutton chunks infused with coarse spiced minced lamb, brown onions, cloves, and whole black cardamom.",
    price: 529,
    category: "Non-Veg",
    image: "https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=800&q=80",
    vegetarian: false,
    spicy: true,
    available: true,
    featured: false,
  },
  {
    name: "Garlic Butter Naan",
    description: "Leavened dough hand-stretched, slapped onto tandoor walls, and slathered with toasted garlic butter and fresh coriander.",
    price: 89,
    category: "Breads",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  },
  {
    name: "Subz Dum Biryani",
    description: "Fragrant aged Basmati rice layered with garden vegetables, saffron milk, and aromatic mint, sealed and steamed in earthen handi.",
    price: 319,
    category: "Rice",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  },
  {
    name: "Kesari Phirni",
    description: "Traditional stone-ground rice pudding infused with saffron threads and cardamom, set in chilled clay earthen sakoras.",
    price: 189,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  },
  {
    name: "Gulab Jamun with Rabri",
    description: "Golden fried khoya dumplings soaked in rose cardamom syrup, served atop a bed of slow-reduced sweetened malai rabri.",
    price: 219,
    category: "Desserts",
    image: "https://images.unsplash.com/photo-1593798603546-b489679ec97b?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  },
  {
    name: "Kulhad Patiala Lassi",
    description: "Thick churned sweet yogurt topped with a layer of clotted cream (malai), chopped pistachios, and saffron dew.",
    price: 149,
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1571006687081-397554904084?auto=format&fit=crop&w=800&q=80",
    vegetarian: true,
    spicy: false,
    available: true,
    featured: false,
  }
];

export const INITIAL_RESERVATIONS = [
  {
    id: "res-demo-1",
    name: "Rajeshwar Verma",
    phone: "+91 98111 22334",
    email: "rajeshwar.verma@example.com",
    date: "2026-09-24",
    time: "20:00",
    guests: 4,
    specialRequest: "Courtyard charpai table preferred for family anniversary",
    status: "confirmed",
    createdAt: new Date().toISOString(),
  },
  {
    id: "res-demo-2",
    name: "Ananya Sharma",
    phone: "+91 98222 33445",
    email: "ananya.sharma@example.com",
    date: "2026-09-25",
    time: "19:30",
    guests: 2,
    specialRequest: "Mild spices for Dal Makhani, window seating",
    status: "pending",
    createdAt: new Date().toISOString(),
  },
  {
    id: "res-demo-3",
    name: "Major Amarjit Singh",
    phone: "+91 98333 44556",
    email: "amarjit.singh@example.com",
    date: "2026-09-26",
    time: "21:00",
    guests: 6,
    specialRequest: "Celebration dinner, tandoor sampler ready upon seating",
    status: "confirmed",
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_MESSAGES = [
  {
    id: "msg-demo-1",
    name: "Pooja Batra",
    email: "pooja.batra@example.com",
    phone: "+91 98444 55667",
    message: "Do you host private culinary events and corporate catering for 40 guests in Sector 17?",
    status: "unread",
    createdAt: new Date().toISOString(),
  },
  {
    id: "msg-demo-2",
    name: "Karan Johal",
    email: "karan.johal@example.com",
    phone: "+91 98555 66778",
    message: "Compliments to the chef for the authentic Sarson Ka Saag. Wanted to check if weekend table booking requires 48 hours notice.",
    status: "read",
    createdAt: new Date().toISOString(),
  }
];
